name: pages_deployment
on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v5
            with:
                python-version: '3.13'
                cache: 'pip'
          - name: install
            run: |
              pip install .
          - name: create notebook_wd
            run: |
              marimo export html-wasm marimo/implementation_wd.py -o deploydir/implementation_wd.html --mode run --no-show-code
          - name: create notebook_at
            run: |
              marimo export html-wasm marimo/implementation_at.py -o deploydir/implementation_at.html --mode run --no-show-code
          - name: create notebook_atwd
            run: |
              marimo export html-wasm marimo/implementation_atwd.py -o deploydir/implementation_atwd.html --mode run --no-show-code
          - name: generate index
            run: |
              python scripts/gen_index.py
          - name: upload pages artifact
            uses: actions/upload-pages-artifact@v3
            with:
              path: deploydir

    deploy:
        needs: build
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        permissions:
            pages: write
            id-token: write

        steps:
            - name: Deploy
              id: deployment
              uses: actions/deploy-pages@v4
              with:
                  artifact_name: github-pages
